import Head from "next/head";
import Image from "next/image";
import { Inter, Ultra } from "next/font/google";
import styles from "@/styles/Home.module.css";
import axios from "axios";
import { useState } from "react";

type message = {
  type: string;
  message: string;
};

export default function Home() {
  const [pets, setPets] = useState([]);
  const [inputVal, setInputVal] = useState("");
  const [chatLogs, setChatLogs] = useState<message[]>([]);

  const clickHandler = async () => {
    const url = "/api/hello";
    const payload = ["miso", "teddy"];

    const obj = await axios.post(url, payload).then((res) => {
      return res.data;
    });

    setPets(obj);

    // alert(`Data: ${data.cat}`);
  };

  const handleSubmit = (event: any) => {
    event.preventDefault();

    setChatLogs((prevChatLogs) => [
      ...prevChatLogs,
      { type: "user", message: inputVal },
    ]);
    console.log("Input value: ", inputVal);

    setInputVal("");
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" text-red-500 font-bold text-center flex flex-col h-screen border-2 border-red-500 w-1/2 mx-auto">
        {/* <button
          className="p-2 rounded bg-black cursor-pointer"
          onClick={clickHandler}
        >
          Click Me!!
        </button>
        <div>
          Pets:
          {pets && (
            <ul>
              {pets.map((pet) => (
                <li>{pet}</li>
              ))}
            </ul>
          )}
        </div> */}

        <h1 className="text-3xl">Chat Logs</h1>

        <div className=" flex-grow p-6">
          {chatLogs && (
            <ul>
              {chatLogs.map((chat, index) => (
                <li key={index}>{chat.message}</li>
              ))}
            </ul>
          )}
        </div>

        <form onSubmit={handleSubmit}>
          <input
            type="text"
            className=" border-2 border-gray-500 rounded"
            placeholder="Type your message..."
            value={inputVal}
            onChange={(e) => setInputVal(e.target.value)}
          />
          <button type="submit" className="hover:bg-gray-200">
            Send
          </button>
        </form>
      </main>
    </>
  );
}
